### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by robjameva** [robjameva/Did-I-Win#3]
Build basic wireframe using XD

- Mobile first
- Determine color scheme
- Font family
- Layout: User input fields, main display to show submitted numbers
- Buttons: Add box button, check score button, clear boxes button
- Inputs: Per quarter display with payout, AFC?NFC box number

**Comment by Keemperor** [comment]
HTML done to minimal specifications, buttons are set and dropdown menus are labeled, grid is generated with a basic format of 1-9 and 0 at the end
